version: 2
jobs:   
  publish:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/$REPO:$CIRCLE_BUILD_NUM .
      - run: docker push $DOCKER_USER/$REPO:$CIRCLE_BUILD_NUM
      
  workflows:
  version: 2
  build_and_test:
    jobs:
      - publish:
          filters:
            branches:
              only: 
                - development
